version: '3'

services:
  db:
    image: mysql:5.6
    container_name: mysql-dev
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo_db
      - MYSQL_USER=hemant
      - MYSQL_PASSWORD=hemant@#123
      - MYSQL_ROOT_HOST=%

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: 'django_server'
    command: bash -c  "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DB_HOST: 'db'
    depends_on:
      - db

volumes:
  mysql_data: