version: '3'

services:
  db:
    restart: always
    image: mysql:5.6
    container_name: django.docker.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo_db
      - MYSQL_USER=hemant
      - MYSQL_PASSWORD=hemant@#123
      - MYSQL_ROOT_HOST=%
      - MYSQL_TCP_PORT=3307
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django.docker.backend
    command: bash -c  "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "9000:8000"
    environment:
      DB_HOST: 'db'
      MYSQL_DATABASE: "demo_db"
      MYSQL_USER: "hemant"
      MYSQL_PASSWORD: "hemant@#123"
      MYSQL_PORT: "3307"
    depends_on:
      - db

volumes:
  mysql_data:
